#################
#JoinTitle
#By MilkAndCookiz
#Version: 1.0.1
#A join title plugin for your server, configurable & functional.
#If you have any suggest, you can contact me on Twitter ! @MilkAndCookiz
#################

#main_title: Change the big title here, for example you can put your server name here.
main_title: "§a§lWelcome To"

#down_title: Change the little title here, for example you can put a welcome message here.
down_title: "§6Void§3OP§bFactions§cPE!"

#time_title: Change the appearance time of the title here. 20 = 1 sec.
time_title: 60
